# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5433/hermes_market
spring.datasource.username=postgres
spring.datasource.password=123456789

# JPA

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Log SQL

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true