CREATE TABLE tb_users(
    id BIGINT GENERATED BY DEFAULT ALWAYS AS IDENTITY PRIMARY KEY ,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status INTEGER NOT NULL,
    role INTEGER NOT NULL,
    birth_date DATE
);

-- Indices para os campos mais buscados
CREATE INDEX idx_users_status ON tb_users(status);
CREATE INDEX idx_users_role ON tb_users(role);

-- Comentários detalhados para os campos
COMMENT ON COLUMN tb_users.status IS '1=Active, 2=Inactive, 3=Blocked';
COMMENT ON COLUMN tb_users.role IS '1=Admin, 2=Client';


