CREATE TABLE tb_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number INTEGER NOT NULL,
    street VARCHAR(100) NOT NULL,
    complement VARCHAR(60),
    neighborhood VARCHAR(60) NOT NULL,
    city VARCHAR(60) NOT NULL,
    state INTEGER NOT NULL,
    zipcode VARCHAR(8) NOT NULL,
    status INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_addresses_user
    FOREIGN KEY(user_id)
    REFERENCES tb_users(id)
);

-- Indices para os campos mais buscados
CREATE INDEX idx_addresses_user_id ON tb_addresses(user_id);
CREATE INDEX idx_addresses_zipcode ON tb_addresses(zipcode);
CREATE INDEX idx_addresses_status ON tb_addresses(status);


-- Comentário detalhado para o campo
COMMENT ON COLUMN tb_addresses.status IS '1=ACTIVE, 2=INACTIVE';