CREATE TABLE tb_orders (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status INTEGER NOT NULL,
    total_price DECIMAL(15, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    payment INTEGER NOT NULL,
    delivery INTEGER NOT NULL,
    address_id BIGINT NOT NULL,

    CONSTRAINT fk_orders_user
    FOREIGN KEY (user_id)
    REFERENCES tb_users(id),

    CONSTRAINT fk_orders_address
    FOREIGN KEY (address_id)
    REFERENCES tb_addresses(id)

);

CREATE INDEX idx_orders_user_id ON tb_orders(user_id);
CREATE INDEX idx_orders_address_id ON tb_orders(address_id);
CREATE INDEX idx_orders_status ON tb_orders(status);

COMMENT ON COLUMN tb_orders.status IS '1=CREATED, 2=PAID, 3=SHIPPED, 4=DELIVERED, 5=CANCELED';
COMMENT ON COLUMN tb_orders.payment IS '1=CASH, 2=PIX, 3=BOLETO, 4=CREDIT_CARD, 5=DEBIT_CARD';
COMMENT ON COLUMN tb_orders.delivery IS '1=PICKUP, 2=HOME_DELIVERY';