CREATE TABLE tb_brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_tb_brands_name ON tb_brands(name);
CREATE INDEX idx_tb_brands_status ON tb_brands(status);

COMMENT ON COLUMN tb_brands.status IS '1=ACTIVE, 2=INACTIVE';