CREATE TABLE tb_categories(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_tb_categories_name ON tb_categories(name);
CREATE INDEX idx_tb_categories_status ON tb_categories(status);

COMMENT ON COLUMN tb_categories.status IS '1=ACTIVE, 2=INACTIVE';