CREATE TABLE tb_products (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price DECIMAL(15, 2) NOT NULL,
    quantity_in_stock INTEGER NOT NULL,
    img_url VARCHAR(255) NOT NULL,
    status INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    category_id BIGINT NOT NULL,
    brand_id BIGINT NOT NULL,

    CONSTRAINT fk_products_category_id
    FOREIGN KEY (category_id)
    REFERENCES tb_categories(id),

    CONSTRAINT fk_products_brand_id
    FOREIGN KEY (brand_id)
    REFERENCES tb_brands(id)
);

CREATE INDEX idx_products_category_id ON tb_products(category_id);
CREATE INDEX idx_products_brand_id ON tb_products(brand_id);
CREATE INDEX idx_products_name ON tb_products(name);
CREATE INDEX idx_products_status ON tb_products(status);

COMMENT ON COLUMN tb_products.status IS '1=ACTIVE, 2=INACTIVE, 3=NO_STOCK';