CREATE TABLE tb_promotions(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    status INTEGER NOT NULL,
    type INTEGER NOT NULL,
    discount_percentage DECIMAL(15,2) NOT NULL,
    min_quantity INTEGER
);

CREATE INDEX idx_promotions_status ON tb_promotions(status);
CREATE INDEX idx_promotions_type ON tb_promotions(type);

COMMENT ON COLUMN tb_promotions.status IS '1=ACTIVE, 2=INACTIVE';
COMMENT ON COLUMN tb_promotions.type IS '1=DIRECT_PRICE, 2=QUANTITY_DISCOUNT';