CREATE TABLE tb_order_items(

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    price DECIMAL(15,2) NOT NULL,

    CONSTRAINT fk_order_items_product_id
    FOREIGN KEY (product_id)
    REFERENCES tb_products(id),

    CONSTRAINT fk_order_items_order_id
    FOREIGN KEY (order_id)
    REFERENCES tb_orders(id)
);

CREATE INDEX idx_order_items_product_id ON tb_order_items(product_id);
CREATE INDEX idx_order_items_order_id ON tb_order_items(order_id);


